name = "MultiProgressManagers"
uuid = "cc0c738e-a464-4ba6-84fc-30e2ce8f9d3d"
authors = ["Kristian Holme <holme.kristian@gmail.com>"]
version = "0.0.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[weakdeps]
Drill = "49b37b9d-a8e6-4364-9144-4677bcb8a7f0"

[extensions]
MultiProgressManagersDrillExt = "Drill"

[compat]
Distributed = "1.11.0"
ProgressMeter = "1.11.0"
